---
language: python
python:
  - "3.8"

env:
  - DATABASE_URI=postgres://postgres:@localhost:5432/test

services:
  - postgresql

before_script:
  - psql -c 'create database test;' -U postgres

install: "pip install -r requirements.txt"

script:
  - nosetests
